# Generated by Django 4.0.6 on 2023-03-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_event_location_alter_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='virtual', max_length=150),
        ),
    ]
