# Generated by Django 4.0.6 on 2023-03-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0005_alter_attendee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
