# Generated by Django 4.0.6 on 2023-03-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0006_alter_attendee_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='fn',
            new_name='first_name',
        ),
    ]
