# Generated by Django 4.0.6 on 2023-03-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0007_rename_f_name_attendee_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='first_name',
            new_name='full_name',
        ),
    ]
